apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sonarqube.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sonarqube.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "sonarqube.name" . }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: sonarqube
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9000
          env:
            - name: SONAR_JDBC_URL
              value: {{ .Values.env.sonarJdbcUrl }}
            - name: SONAR_JDBC_USERNAME
              value: {{ .Values.env.sonarJdbcUsername }}
            - name: SONAR_JDBC_PASSWORD
              value: {{ .Values.env.sonarJdbcPassword }}
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          livenessProbe:
            httpGet:
              path: /about
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /about
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
            - name: sonarqube-extensions
              mountPath: /opt/sonarqube/extensions
            - name: sonarqube-logs
              mountPath: /opt/sonarqube/logs
            - name: sonarqube-temp
              mountPath: /opt/sonarqube/temp
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.dataClaim }}
        - name: sonarqube-extensions
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.extensionsClaim }}
        - name: sonarqube-logs
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.logsClaim }}
        - name: sonarqube-temp
          emptyDir: {}
