apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: {{ .Release.Namespace }}
  labels:
    app: sonarqube
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: sonarqube
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP
