apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: fix-permissions
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              mkdir -p /opt/sonarqube/data/es7 /opt/sonarqube/extensions /opt/sonarqube/logs /opt/sonarqube/temp && \
              chown -R 1000:1000 /opt/sonarqube
          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
            - name: sonarqube-extensions
              mountPath: /opt/sonarqube/extensions
            - name: sonarqube-logs
              mountPath: /opt/sonarqube/logs
            - name: sonarqube-temp
              mountPath: /opt/sonarqube/temp
      containers:
        - name: sonarqube
          image: "{{ .Values.sonarqube.image.repository }}:{{ .Values.sonarqube.image.tag }}"
          imagePullPolicy: "{{ .Values.sonarqube.image.pullPolicy }}"
          ports:
            - containerPort: 9000
          env:
            - name: SONAR_JDBC_URL
              value: "{{ .Values.sonarqube.env.SONAR_JDBC_URL }}"
            - name: SONAR_JDBC_USERNAME
              value: "{{ .Values.sonarqube.env.SONAR_JDBC_USERNAME }}"
            - name: SONAR_JDBC_PASSWORD
              value: "{{ .Values.sonarqube.env.SONAR_JDBC_PASSWORD }}"
            - name: SONAR_JVM_OPTS
              value: "{{ .Values.sonarqube.env.SONAR_JVM_OPTS }}"
          resources:
            requests:
              cpu: "{{ .Values.sonarqube.resources.requests.cpu }}"
              memory: "{{ .Values.sonarqube.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.sonarqube.resources.limits.cpu }}"
              memory: "{{ .Values.sonarqube.resources.limits.memory }}"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /about
              port: 9000
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /about
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
            - name: sonarqube-extensions
              mountPath: /opt/sonarqube/extensions
            - name: sonarqube-logs
              mountPath: /opt/sonarqube/logs
            - name: sonarqube-temp
              mountPath: /opt/sonarqube/temp
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data-pvc
        - name: sonarqube-extensions
          persistentVolumeClaim:
            claimName: sonarqube-extensions-pvc
        - name: sonarqube-logs
          persistentVolumeClaim:
            claimName: sonarqube-logs-pvc
        - name: sonarqube-temp
          emptyDir: {}
