apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  type: {{ .Values.sonarqube.type }}
  selector:
    app: sonarqube
  ports:
    - port: {{ .Values.sonarqube.port }}
      targetPort: {{ .Values.sonarqube.port }}
