sonarqube:
  image:
    repository: sonarqube
    tag: 9.9.4-community
    pullPolicy: Always  # CKV_K8S_15 requires Always

  env:
    SONAR_JDBC_URL: jdbc:postgresql://your-postgres-host/sonarqube
    SONAR_JDBC_USERNAME: sonaruser
    SONAR_JDBC_PASSWORD: sonarpassword

  resources:
    requests:
      cpu: "500m"      # CKV_K8S_10: CPU requests
      memory: "1Gi"    # CKV_K8S_12: Memory requests
    limits:
      cpu: "1000m"     # CKV_K8S_11: CPU limits
      memory: "2Gi"    # CKV_K8S_13: Memory limits

  persistence:
    data:
      existingClaim: sonarqube-data-pvc
    extensions:
      existingClaim: sonarqube-extensions-pvc
    logs:
      existingClaim: sonarqube-logs-pvc
