postgres:
  image:
    repository: postgres
    tag: "15.2"
    pullPolicy: Always
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  persistence:
    size: 8Gi
    storageClass: standard
  auth:
    database: sonarqube
    username: sonar
    password: sonarpass

sonarqube:
  image:
    repository: sonarqube
    tag: "9.9.4-community"
    pullPolicy: Always
