sonarqube:
  image:
    repository: sonarqube
    tag: 9.9.9
  port: 9000
  storage:
    data: 20Gi
    extensions: 2Gi
    logs: 1Gi

postgres:
  image: postgres:15
  user: sonar
  password: sonarpass
  database: sonarqube
  port: 5432
  storage: 5Gi

ingress:
  enabled: true
  hostname: sonarqube.local
  className: nginx
