sonarqube:
  image:
    repository: sonarqube
    tag: 9.9.1-community
    pullPolicy: Always

  env:
    SONAR_JDBC_URL: jdbc:postgresql://postgresql:5432/sonarqube
    SONAR_JDBC_USERNAME: sonar
    SONAR_JDBC_PASSWORD: sonar

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  persistence:
    data:
      existingClaim: sonarqube-data-pvc
    extensions:
      existingClaim: sonarqube-extensions-pvc
    logs:
      existingClaim: sonarqube-logs-pvc
